use serde_json::{Map, Value};

pub fn emit_config_ts(schema: &Value) -> Result<String, String> {
    let root = schema.as_object().ok_or("schema must be an object")?;
    let defs = root
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or("schema must have $defs")?;
    let required = root
        .get("required")
        .and_then(Value::as_array)
        .map(|arr| arr.iter().filter_map(Value::as_str).collect::<Vec<_>>())
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str("// Generated by oasts-gen — do not edit.\n\n");

    for (name, def) in def_emission_order(defs) {
        if is_exclusive_one_of(&def) {
            emit_exclusive_union_type(&mut out, &name, &def)?;
        } else if is_any_of(&def) {
            emit_any_of_type(&mut out, &name, &def, defs)?;
        } else {
            emit_interface(&mut out, &name, &def, defs, &[])?;
        }
    }

    if let Some(desc) = root.get("description").and_then(Value::as_str) {
        out.push_str(&format!("/** {desc} */\n"));
    }
    out.push_str("export interface UserConfig {\n");
    let props = root
        .get("properties")
        .and_then(Value::as_object)
        .ok_or("root must have properties")?;
    for (key, prop) in props {
        let is_required = required.contains(&key.as_str());
        let ts_type = schema_to_ts(prop, defs)?;
        if is_required {
            out.push_str(&format!("  {}: {};\n", format_key(key), ts_type));
        } else {
            out.push_str(&format!("  {}?: {};\n", format_key(key), ts_type));
        }
    }
    out.push_str("}\n\n");

    out.push_str("/** Identity function providing `UserConfig` typing for script configs. */\n");
    out.push_str("export function defineConfig(config: UserConfig): UserConfig {\n");
    out.push_str("  return config;\n");
    out.push_str("}\n");

    Ok(out)
}

fn def_emission_order(defs: &Map<String, Value>) -> Vec<(String, Value)> {
    let mut types: Vec<(String, Value)> = Vec::new();
    let mut interfaces: Vec<(String, Value)> = Vec::new();

    for (name, def) in defs {
        if is_string_enum(def) {
            continue;
        }
        if is_exclusive_one_of(def) || is_any_of(def) {
            types.push((name.clone(), def.clone()));
        } else if is_object(def) {
            interfaces.push((name.clone(), def.clone()));
        }
    }

    let mut order = types;
    order.extend(interfaces);
    order
}

fn is_string_enum(schema: &Value) -> bool {
    schema.as_object().is_some_and(|obj| {
        obj.get("enum").is_some() && obj.get("type") == Some(&Value::String("string".into()))
    })
}

fn is_exclusive_one_of(schema: &Value) -> bool {
    let Some(obj) = schema.as_object() else {
        return false;
    };
    let Some(branches) = obj.get("oneOf").and_then(Value::as_array) else {
        return false;
    };
    branches.iter().all(|b| {
        b.as_object().is_some_and(|o| {
            o.get("type") == Some(&Value::String("object".into()))
                && o.get("additionalProperties") == Some(&Value::Bool(false))
        })
    })
}

fn is_any_of(schema: &Value) -> bool {
    schema
        .as_object()
        .is_some_and(|obj| obj.get("anyOf").is_some())
}

fn is_object(schema: &Value) -> bool {
    schema
        .as_object()
        .is_some_and(|obj| obj.get("type") == Some(&Value::String("object".into())))
}

fn emit_exclusive_union_type(out: &mut String, name: &str, schema: &Value) -> Result<(), String> {
    emit_jsdoc(out, schema);
    let branches = schema["oneOf"]
        .as_array()
        .ok_or_else(|| format!("{name}: oneOf must be an array"))?;

    let all_keys: Vec<String> = branches
        .iter()
        .flat_map(|b| {
            b.get("properties")
                .and_then(Value::as_object)
                .map(|p| p.keys().cloned().collect::<Vec<_>>())
                .unwrap_or_default()
        })
        .collect();

    let empty = Map::new();
    let mut parts: Vec<String> = Vec::new();
    for branch in branches {
        let props = branch
            .get("properties")
            .and_then(Value::as_object)
            .unwrap_or(&empty);
        let required: Vec<&str> = branch
            .get("required")
            .and_then(Value::as_array)
            .map(|arr| arr.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();

        let mut fields: Vec<String> = Vec::new();
        for (key, prop) in props {
            let ts_type = primitive_type(prop);
            if required.contains(&key.as_str()) {
                fields.push(format!("{key}: {ts_type}"));
            } else {
                fields.push(format!("{key}?: {ts_type}"));
            }
        }

        for key in &all_keys {
            if !props.contains_key(key) {
                fields.push(format!("{key}?: never"));
            }
        }

        parts.push(format!("{{ {} }}", fields.join("; ")));
    }

    out.push_str(&format!("export type {name} = {};\n\n", parts.join(" | ")));
    Ok(())
}

fn emit_any_of_type(
    out: &mut String,
    name: &str,
    schema: &Value,
    defs: &Map<String, Value>,
) -> Result<(), String> {
    emit_jsdoc(out, schema);
    let branches = schema["anyOf"]
        .as_array()
        .ok_or_else(|| format!("{name}: anyOf must be an array"))?;

    let ts_parts: Vec<String> = branches
        .iter()
        .map(|b| schema_to_ts(b, defs))
        .collect::<Result<_, _>>()?;

    out.push_str(&format!(
        "export type {name} = {};\n\n",
        ts_parts.join(" | ")
    ));
    Ok(())
}

fn emit_interface(
    out: &mut String,
    name: &str,
    schema: &Value,
    defs: &Map<String, Value>,
    required: &[&str],
) -> Result<(), String> {
    emit_jsdoc(out, schema);
    let props = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| format!("{name}: object must have properties"))?;

    out.push_str(&format!("export interface {name} {{\n"));
    for (key, prop) in props {
        let ts_type = schema_to_ts(prop, defs)?;
        if required.contains(&key.as_str()) {
            out.push_str(&format!("  {}: {};\n", format_key(key), ts_type));
        } else {
            out.push_str(&format!("  {}?: {};\n", format_key(key), ts_type));
        }
    }
    out.push_str("}\n\n");
    Ok(())
}

fn schema_to_ts(schema: &Value, defs: &Map<String, Value>) -> Result<String, String> {
    let obj = match schema.as_object() {
        Some(o) => o,
        None if schema.as_bool() == Some(true) => return Ok("unknown".into()),
        _ => return Err(format!("unexpected schema: {schema}")),
    };

    if obj.is_empty() {
        return Ok("unknown".into());
    }

    if let Some(ref_path) = obj.get("$ref").and_then(Value::as_str) {
        let name = ref_path
            .strip_prefix("#/$defs/")
            .ok_or_else(|| format!("unsupported $ref: {ref_path}"))?;
        if let Some(def) = defs.get(name)
            && is_string_enum(def)
        {
            return inline_string_enum(def);
        }
        return Ok(name.into());
    }

    if let Some(const_val) = obj.get("const") {
        return Ok(const_to_ts(const_val));
    }

    if let Some(enum_arr) = obj.get("enum") {
        return inline_enum(enum_arr);
    }

    if let Some(any_of) = obj.get("anyOf").and_then(Value::as_array) {
        let parts: Vec<String> = any_of
            .iter()
            .map(|b| schema_to_ts(b, defs))
            .collect::<Result<_, _>>()?;
        return Ok(parts.join(" | "));
    }

    if let Some(one_of) = obj.get("oneOf").and_then(Value::as_array) {
        let parts: Vec<String> = one_of
            .iter()
            .map(|b| schema_to_ts(b, defs))
            .collect::<Result<_, _>>()?;
        return Ok(parts.join(" | "));
    }

    if let Some(type_val) = obj.get("type") {
        match type_val.as_str() {
            Some("string") => return Ok("string".into()),
            Some("boolean") => return Ok("boolean".into()),
            Some("integer" | "number") => return Ok("number".into()),
            Some("array") => {
                let items = obj.get("items").unwrap_or(&Value::Bool(true));
                let item_type = schema_to_ts(items, defs)?;
                return Ok(format!("{item_type}[]"));
            }
            Some("object") => {
                if let Some(props) = obj.get("properties").and_then(Value::as_object) {
                    let fields: Vec<String> = props
                        .iter()
                        .map(|(k, v)| {
                            let ts = schema_to_ts(v, defs)?;
                            Ok(format!("{k}?: {ts}"))
                        })
                        .collect::<Result<_, String>>()?;
                    return Ok(format!("{{ {} }}", fields.join("; ")));
                }
                // A map schema (additionalProperties is a value schema, not `false`) keeps its
                // value type so `Record<string, string>` survives instead of collapsing to unknown.
                if let Some(additional) = obj.get("additionalProperties").and_then(Value::as_object)
                {
                    let value_type = schema_to_ts(&Value::Object(additional.clone()), defs)?;
                    return Ok(format!("Record<string, {value_type}>"));
                }
                return Ok("Record<string, unknown>".into());
            }
            _ => {}
        }
        if let Some(arr) = type_val.as_array() {
            let parts: Vec<String> = arr
                .iter()
                .filter_map(Value::as_str)
                .map(|t| match t {
                    "string" => "string".into(),
                    "boolean" => "boolean".into(),
                    "integer" | "number" => "number".into(),
                    other => other.into(),
                })
                .collect();
            return Ok(parts.join(" | "));
        }
    }

    Ok("unknown".into())
}

fn const_to_ts(value: &Value) -> String {
    match value {
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("\"{s}\""),
        Value::Bool(b) => b.to_string(),
        Value::Null => "null".into(),
        _ => "unknown".into(),
    }
}

fn inline_string_enum(schema: &Value) -> Result<String, String> {
    let arr = schema
        .get("enum")
        .and_then(Value::as_array)
        .ok_or("string enum missing enum array")?;
    inline_enum(&Value::Array(arr.clone()))
}

fn inline_enum(arr: &Value) -> Result<String, String> {
    let values = arr.as_array().ok_or("enum must be an array")?;
    let parts: Vec<String> = values.iter().map(const_to_ts).collect();
    Ok(parts.join(" | "))
}

fn emit_jsdoc(out: &mut String, schema: &Value) {
    if let Some(desc) = schema.get("description").and_then(Value::as_str) {
        out.push_str(&format!("/** {desc} */\n"));
    }
}

fn primitive_type(schema: &Value) -> String {
    if let Some(value) = schema.get("const") {
        return const_to_ts(value);
    }
    match schema.get("type").and_then(Value::as_str) {
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("integer" | "number") => "number".into(),
        _ => "unknown".into(),
    }
}

fn format_key(key: &str) -> String {
    if key.contains('-') || key.contains('.') {
        format!("\"{key}\"")
    } else {
        key.into()
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn test_defs() -> Map<String, Value> {
        let mut defs = Map::new();
        defs.insert(
            "MyEnum".into(),
            json!({"type": "string", "enum": ["a", "b"]}),
        );
        defs.insert(
            "MyObj".into(),
            json!({"type": "object", "properties": {"x": {"type": "string"}}}),
        );
        defs
    }

    #[test]
    fn string_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "string"}), &defs).unwrap(),
            "string"
        );
    }

    #[test]
    fn boolean_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "boolean"}), &defs).unwrap(),
            "boolean"
        );
    }

    #[test]
    fn integer_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "integer"}), &defs).unwrap(),
            "number"
        );
    }

    #[test]
    fn number_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "number"}), &defs).unwrap(),
            "number"
        );
    }

    #[test]
    fn const_integer() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "integer", "const": 1}), &defs).unwrap(),
            "1"
        );
    }

    #[test]
    fn const_string() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"const": "hello"}), &defs).unwrap(),
            "\"hello\""
        );
    }

    #[test]
    fn const_bool() {
        assert_eq!(const_to_ts(&json!(true)), "true");
    }

    #[test]
    fn const_null() {
        assert_eq!(const_to_ts(&json!(null)), "null");
    }

    #[test]
    fn const_array_fallback() {
        assert_eq!(const_to_ts(&json!([1, 2])), "unknown");
    }

    #[test]
    fn enum_inline() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "string", "enum": ["x", "y"]}), &defs).unwrap(),
            "\"x\" | \"y\""
        );
    }

    #[test]
    fn ref_to_string_enum_inlines() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"$ref": "#/$defs/MyEnum"}), &defs).unwrap(),
            "\"a\" | \"b\""
        );
    }

    #[test]
    fn ref_to_object_uses_name() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"$ref": "#/$defs/MyObj"}), &defs).unwrap(),
            "MyObj"
        );
    }

    #[test]
    fn array_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"type": "array", "items": {"type": "string"}}),
                &defs
            )
            .unwrap(),
            "string[]"
        );
    }

    #[test]
    fn array_without_items() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "array"}), &defs).unwrap(),
            "unknown[]"
        );
    }

    #[test]
    fn empty_schema_is_unknown() {
        let defs = test_defs();
        assert_eq!(schema_to_ts(&json!({}), &defs).unwrap(), "unknown");
    }

    #[test]
    fn true_schema_is_unknown() {
        let defs = test_defs();
        assert_eq!(schema_to_ts(&json!(true), &defs).unwrap(), "unknown");
    }

    #[test]
    fn any_of() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"anyOf": [{"type": "boolean"}, {"type": "string"}]}),
                &defs
            )
            .unwrap(),
            "boolean | string"
        );
    }

    #[test]
    fn one_of() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"oneOf": [{"type": "string"}, {"type": "number"}]}),
                &defs
            )
            .unwrap(),
            "string | number"
        );
    }

    #[test]
    fn type_array() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": ["string", "integer"]}), &defs).unwrap(),
            "string | number"
        );
    }

    #[test]
    fn object_inline() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"type": "object", "properties": {"a": {"type": "string"}}}),
                &defs
            )
            .unwrap(),
            "{ a?: string }"
        );
    }

    #[test]
    fn object_no_properties() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": "object"}), &defs).unwrap(),
            "Record<string, unknown>"
        );
    }

    #[test]
    fn object_map_keeps_value_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"type": "object", "additionalProperties": {"type": "string"}}),
                &defs
            )
            .unwrap(),
            "Record<string, string>"
        );
    }

    #[test]
    fn object_closed_without_properties_is_unknown_record() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(
                &json!({"type": "object", "additionalProperties": false}),
                &defs
            )
            .unwrap(),
            "Record<string, unknown>"
        );
    }

    #[test]
    fn format_key_dollar_prefix_stays_bare() {
        assert_eq!(format_key("$schema"), "$schema");
    }

    #[test]
    fn format_key_plain() {
        assert_eq!(format_key("input"), "input");
    }

    #[test]
    fn format_key_hyphen() {
        assert_eq!(format_key("my-key"), "\"my-key\"");
    }

    #[test]
    fn format_key_dot() {
        assert_eq!(format_key("my.key"), "\"my.key\"");
    }

    #[test]
    fn unsupported_ref() {
        let defs = test_defs();
        assert!(schema_to_ts(&json!({"$ref": "external.json"}), &defs).is_err());
    }

    #[test]
    fn non_object_schema_error() {
        let defs = test_defs();
        assert!(schema_to_ts(&json!(false), &defs).is_err());
    }

    #[test]
    fn emit_config_ts_produces_valid_output() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).expect("should produce TypeScript");
        assert!(ts.starts_with("// Generated by oasts-gen"));
        assert!(ts.contains("export interface UserConfig"));
        assert!(ts.contains("export function defineConfig"));
        assert!(ts.contains("export type Input"));
        assert!(ts.contains("export type ArtifactSetting"));
        assert!(ts.contains("export interface ArtifactOptions"));
        assert!(ts.contains("schemaVersion: 1;"));
        assert!(ts.contains("input: Input;"));
        assert!(ts.contains("output: string;"));
    }

    #[test]
    fn input_is_exclusive_union_with_never() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        assert!(
            ts.contains("path: string; url?: never") && ts.contains("url: string; path?: never"),
            "Input should be an exclusive union with never"
        );
    }

    #[test]
    fn deferred_blocks_are_unknown() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        for key in ["specs", "shared", "watch", "ci"] {
            assert!(
                ts.contains(&format!("{key}?: unknown")),
                "deferred block {key} should be optional unknown"
            );
        }
    }

    #[test]
    fn the_remote_block_is_typed() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        assert!(ts.contains("remote?: RemoteConfig;"));
        assert!(ts.contains("allowHosts?: string[];"));
        assert!(ts.contains("integrity?: Record<string, string>;"));
    }

    #[test]
    fn client_and_validation_blocks_are_typed() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        assert!(ts.contains("client?: RawClient;"));
        assert!(ts.contains("validation?: RawValidation;"));
        assert!(ts.contains("export interface FetchDefaults"));
        assert!(ts.contains("credentials?: \"omit\" | \"same-origin\" | \"include\";"));
        assert!(ts.contains("source: \"runtime\""));
        assert!(ts.contains("source: \"server\""));
        assert!(ts.contains("source: \"literal\""));
        assert!(!ts.contains("transport?:"));
    }

    #[test]
    fn naming_overrides_render_as_string_records() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        assert!(ts.contains("export interface NameOverrides"));
        assert!(ts.contains("schemas?: Record<string, string>;"));
        assert!(ts.contains("operations?: Record<string, string>;"));
        assert!(ts.contains("overrides?: NameOverrides;"));
    }

    #[test]
    fn string_enums_are_inlined() {
        let schema = crate::schema::config_schema();
        let ts = emit_config_ts(&schema).unwrap();
        assert!(
            !ts.contains("export type EnumRepresentation")
                && !ts.contains("export interface EnumRepresentation"),
            "string enums should not appear as named types"
        );
        assert!(ts.contains("\"literal\" | \"const\""));
        assert!(ts.contains("typeCase?: \"pascal\";"));
        assert!(ts.contains("propertyCase?: \"preserve\";"));
        assert!(ts.contains("importExtension?: \".js\" | \"none\";"));
        assert!(ts.contains("format?: \"deterministic\";"));
    }

    #[test]
    fn emit_rejects_missing_defs() {
        let schema = json!({"type": "object"});
        assert!(emit_config_ts(&schema).is_err());
    }

    #[test]
    fn emit_rejects_non_object() {
        assert!(emit_config_ts(&json!("not an object")).is_err());
    }

    #[test]
    fn emit_rejects_missing_properties() {
        let schema = json!({"$defs": {}});
        assert!(emit_config_ts(&schema).is_err());
    }

    #[test]
    fn exclusive_union_error_on_bad_one_of() {
        let mut out = String::new();
        let schema = json!({"oneOf": "not an array"});
        assert!(emit_exclusive_union_type(&mut out, "Test", &schema).is_err());
    }

    #[test]
    fn any_of_type_error_on_bad_any_of() {
        let mut out = String::new();
        let defs = test_defs();
        let schema = json!({"anyOf": "not an array"});
        assert!(emit_any_of_type(&mut out, "Test", &schema, &defs).is_err());
    }

    #[test]
    fn emit_interface_error_on_missing_properties() {
        let mut out = String::new();
        let defs = test_defs();
        let schema = json!({"type": "object"});
        assert!(emit_interface(&mut out, "Test", &schema, &defs, &[]).is_err());
    }

    #[test]
    fn is_string_enum_detects_correctly() {
        assert!(is_string_enum(&json!({"type": "string", "enum": ["a"]})));
        assert!(!is_string_enum(&json!({"type": "object"})));
        assert!(!is_string_enum(&json!("not an object")));
    }

    #[test]
    fn is_exclusive_one_of_detects_correctly() {
        assert!(is_exclusive_one_of(&json!({
            "oneOf": [
                {"type": "object", "additionalProperties": false, "properties": {"a": {"type": "string"}}},
                {"type": "object", "additionalProperties": false, "properties": {"b": {"type": "string"}}}
            ]
        })));
        assert!(!is_exclusive_one_of(
            &json!({"oneOf": [{"type": "string"}]})
        ));
        assert!(!is_exclusive_one_of(&json!({"type": "object"})));
        assert!(!is_exclusive_one_of(&json!("not an object")));
    }

    #[test]
    fn is_any_of_detects_correctly() {
        assert!(is_any_of(&json!({"anyOf": []})));
        assert!(!is_any_of(&json!({"type": "string"})));
        assert!(!is_any_of(&json!("not an object")));
    }

    #[test]
    fn is_object_detects_correctly() {
        assert!(is_object(&json!({"type": "object"})));
        assert!(!is_object(&json!({"type": "string"})));
        assert!(!is_object(&json!("not an object")));
    }

    #[test]
    fn inline_string_enum_error_on_missing() {
        assert!(inline_string_enum(&json!({"type": "string"})).is_err());
    }

    #[test]
    fn inline_enum_error_on_non_array() {
        assert!(inline_enum(&json!("not an array")).is_err());
    }

    #[test]
    fn primitive_type_fallback() {
        assert_eq!(primitive_type(&json!({})), "unknown");
    }

    #[test]
    fn primitive_type_boolean() {
        assert_eq!(primitive_type(&json!({"type": "boolean"})), "boolean");
    }

    #[test]
    fn primitive_type_integer() {
        assert_eq!(primitive_type(&json!({"type": "integer"})), "number");
    }

    #[test]
    fn primitive_type_number() {
        assert_eq!(primitive_type(&json!({"type": "number"})), "number");
    }

    #[test]
    fn exclusive_union_with_optional_property() {
        let mut out = String::new();
        let schema = json!({
            "oneOf": [
                {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {"a": {"type": "string"}, "c": {"type": "boolean"}},
                    "required": ["a"]
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {"b": {"type": "integer"}},
                    "required": ["b"]
                }
            ]
        });
        emit_exclusive_union_type(&mut out, "Test", &schema).unwrap();
        assert!(out.contains("c?: boolean"));
        assert!(out.contains("a: string"));
        assert!(out.contains("b: number"));
    }

    #[test]
    fn emit_interface_with_required_fields() {
        let mut out = String::new();
        let defs = test_defs();
        let schema = json!({"type": "object", "properties": {"x": {"type": "string"}, "y": {"type": "number"}}});
        emit_interface(&mut out, "Test", &schema, &defs, &["x"]).unwrap();
        assert!(out.contains("x: string"));
        assert!(out.contains("y?: number"));
    }

    #[test]
    fn type_array_with_unknown_type() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": ["string", "custom"]}), &defs).unwrap(),
            "string | custom"
        );
    }

    #[test]
    fn unknown_fallback_schema() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"minLength": 5}), &defs).unwrap(),
            "unknown"
        );
    }

    #[test]
    fn unknown_type_value_fallback() {
        let defs = test_defs();
        assert_eq!(
            schema_to_ts(&json!({"type": 42}), &defs).unwrap(),
            "unknown"
        );
    }
}
